keys:
  - &titouan 1747A2739C3A398E30309BF49E14FC5969AF7844
  - &laptop age1ma7clz2l7v2jqzr9z0pvyjtau8ca3uquk54uj5ah4h37uujzkquq38nwqk

creation_rules:
  - path_regex: Host/laptop/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *titouan
        age:
          - *laptop
  - path_regex: Home/titouan/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *titouan
        age:
          - *laptop
  - path_regex: Lib/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *titouan
        age:
          - *laptop
    
